blog/urls.py
from django.urls import path


from .views import (
    PostListView,
    PostDetailView,
    # PostCreateView,
    # PostUpdateView,
    # PostDeleteView,
    # UserPostListView,
    about_view,
)

app_name = "blog"
urlpatterns = [
    path("", PostListView.as_view(), name="blog_home"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("about/", about_view, name="blog_about"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("blog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("users.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import register_view, profile_view, profile_update_view

app_name = "users"
urlpatterns = [
    path("register/", register_view, name="register"),
    path("profile/<int:id>/", profile_view, name="profile"),
    path("profile/<int:id>/update/", profile_update_view, name="profile_update"),
]

blog/models.py
from django.db import models
from hitcount.models import HitCount, HitCountMixin
from django.contrib.contenttypes.fields import GenericRelation
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from ckeditor.fields import RichTextField

import readtime


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = RichTextField()
    image = models.ImageField(default="blog-post.jpg", upload_to="post_pics")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    hit_count_generic = GenericRelation(
        HitCount,
        object_id_field="object_pk",
        related_query_name="hit_count_generic_relation",
    )

    def get_readtime(self):
        result = readtime.of_text(self.content)
        return result.text

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        super(Post, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 500 or img.width > 500:
            output_size = (500, 500)
            img.thumbnail(output_size)
            img.save(self.image.path)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("blog:blog_home")

blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={"placeholder": "Max 100 Characters"}),
    )

    class Meta:
        model = Comment
        fields = ("comment",)

blog/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views import View
from hitcount.views import HitCountDetailView

from .models import Post
from .forms import CommentForm


class PostListView(ListView):
    model = Post
    template_name = "blog/home.html"
    context_object_name = "posts"
    ordering = "-date_posted"
    paginate_by = 5


class CommentGet(HitCountDetailView):
    model = Post
    template_name = "blog/post_detail.html"
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super(CommentGet, self).get_context_data(**kwargs)
        context["form"] = CommentForm()
        context["form.instance.author"] = self.request.user
        return context


class CommentPost(LoginRequiredMixin, SingleObjectMixin, FormView):
    model = Post
    form_class = CommentForm
    template_name = "blog/post_detail.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.author = self.request.user
        comment = form.save(commit=False)
        comment.post = self.object
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        post = self.get_object()
        return reverse("blog:post_detail", kwargs={"pk": post.pk})


class PostDetailView(View):
    def get(self, request, *args, **kwargs):
        view = CommentGet.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentPost.as_view()
        return view(request, *args, **kwargs)


def about_view(request):
    return render(request, "blog/about.html", {})

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block title %}Feuer | About{% endblock title %}

{% block content %}
    <div class="content-section">
        <p>Mening ismim Hojiakbar, Toshkent viloyati Angren shahridanman. Toshkent shahridagi Xalqaro Westminster Universitetining 2-kurs talabasiman. Soham moliya va moliyaviy texnologiyalari bo'lsada, o'zimning aniq fanlar, ayniqsa fizika va komputer texnologiyalariga qiziqishim baland.</p>
        <p>Bu <strong>Python</strong> dasturlash tilining <strong>Django</strong>  nomli veb-framevorki orqali yartaligan shaxsiy blogdir. Bu mening ilk ko'zga ko'rinarli (yoki rezyumega qo'ysa bo'ladigan :D) proyektimdir. Saytning asosiy qismi YouTubedagi <a href="https://youtu.be/UmljXZIypDc" target="_blank">CoreyMS</a>ning Django haqidagi videolariga asoslangan. O'zim bir qancha yangicha xususiyatlarini qo'shdim.</p>
        <p>Sayt haqida fikr-mulohazalaringiz bo'lsa, <a href="https://t.me/HBarotov/"  target="_blank">Telegram</a> yoki <a href="https://github.com/HBarotov" target="_blank">GitHub</a>da qoldirishingiz mumkin. Sizning fikrlaringiz men uchun qadrli :)</p>
    </div>
    <hr>
    <div class="content-section">
        <p>Hey, I am Hojiakbar, from Angren, Tashkent Region. I am a sophomore at WIUT. Though I study finance and fintech, my passion lies in STEM, especially physics and IT. </p>
        <p>This blog was created with <strong>Django</strong>, a web-framework of <strong>Python</strong>. The blog is my first project, which is worth adding to my CV :D. Anyways, The Django playlist of <a href="https://youtu.be/UmljXZIypDc" target="_blank">CoreyMS</a> on YouTube is the backbone of this site, though I added quite a few features myself.</p>
        <p>Any suggestions? Reach me at <a href="https://t.me/HBarotov/"  target="_blank">Telegram</a> or <a href="https://github.com/HBarotov" target="_blank">GitHub</a>. I appreciate them :)</p>
    </div>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
{% load humanize %}
{% load hitcount_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="author" content="Hojiakbar Barotov">
    <meta name="description" content="Feuer Blog by Hojiakbar Barotov. My first serious project in the backend development.">
    <meta name="keywords" content="Feuer Blog, Hojiakbar Barotov">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/68efd3df5a.js" crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'blog:blog_home' %}">Feuer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'blog:blog_home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'blog:blog_about' %}">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'users:profile' request.user.id %}">
                                {{ request.user.first_name|title }}
                            </a>
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a> 
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container mt-3">
        <div class="row">
            
            <div class="col-md-1">
                
            </div>
            <div class="col-md-10">
                {% if breadcrumbs %}
                    <div class="mb-4">
                        {% include "dynamic_breadcrumbs/breadcrumbs.html" with breadcrumbs=breadcrumbs %}
                    </div>
                {% endif %}
                {% if messages %}
                    {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{ message }}
                            </div>
                    {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>

    <footer class="content-section footer">
        <div class="container flex">
            <h4><a href="{% url 'blog:blog_home' %}">Feuer</a></h4>
            <p class='text-muted mb-0'>2023 by Hojiakbar</p>
            <div class="social">
                <a href="https://t.me/HBarotov/" target="_blank"><i class="fa-brands fa-telegram fa-2x"></i></a>
                <a href="https://github.com/HBarotov" target="_blank" style="color:black"><i class="fa-brands fa-github fa-2x"></i></a>
                <a href="https://www.linkedin.com/in/hojiakbar-barotov/" target="_blank"><i class="fa-brands fa-linkedin fa-2x"></i></a>
            </div>
            </div>
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load humanize %}
{% load hitcount_tags %}
{% block title %}Feuer | Home{% endblock title %}

{% block content %}
    {% for post in posts %}
        <article class="media content-section">
            <a href="{% url 'users:profile' post.author.id %}"><img src="{{ post.author.profile.image.url }}" class="rounded-circle article-img" alt="Profile"></a>
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'users:profile' post.author.id %}"><i class="fa-solid fa-user"></i> {{ post.author.first_name }}</a>
                    <div>
                        <small class="text-muted"><i class="fa-solid fa-pen"></i>{{ post.date_posted|date:'H:i, d/m/Y' }}</small> &middot; 
                        <small class="text-muted"><i class="fa-regular fa-eye"></i>{% get_hit_count for post %}</small> &middot; 
                        <small class="text-muted"><i class="fa-regular fa-comments"></i>{{ post.comment_set.count }}</small>
                    </div>     
                </div>
                <h3><a class="article-title" href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h3>
                <p class="article-content">{{ post.content|truncatechars_html:100|safe }}</p>
            </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load hitcount_tags %}
{% block title %}{{ post.title|title }}{% endblock title %}

{% block content %} 
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata-post">
                <a href="{% url 'users:profile' post.author.id %}"><img src="{{ post.author.profile.image.url }}" class="rounded-circle article-img" alt="Profile {{ post.author.username }}"></a>
                <div class="article-metadata-post-meta">
                    <a class="mr-2" href="{% url 'users:profile' post.author.id %}"><i class="fa-solid fa-user"></i> {{ post.author.first_name }}</a>
                    <div>
                        <small class="text-muted"><i class="fa-solid fa-pen"></i>{{ post.date_posted|date:'H:i, d/m/Y' }}</small> &middot; 
                        <small class="text-muted"><i class="fa-regular fa-eye"></i>{% get_hit_count for post %}</small> &middot;
                        <small class="text-muted"><i class="fa-regular fa-comments"></i>{{ post.comment_set.count }}</small> &middot;
                        <small class="text-muted"></i>{{ post.get_readtime }} read</small>
                    </div>
                </div>
            </div>
            <h2 class="article-title mb-3">{{ post.title }}</h2>
            <img src="{{ post.image.url }}" class="post-img" alt="Profile">
            <p class="article-content mt-4">{{ post.content|safe }}</p>

            <h4 class="mt-5">Comments({{ post.comment_set.count }})</h4>
            {% for comment in post.comment_set.all reversed %}
                <div class="article-metadata-post-comment">
                    <div><p class="m-0 text-muted">{{ comment }}</p></div>
                    <div class="article-metadata-post-comment-meta">
                        <div class="article-metadata-post-meta">
                            <a class="mr-2" href="{% url 'users:profile' comment.author.id %}"><i class="fa-solid fa-user"></i> {{ comment.author.first_name }}</a>
                            <div>
                                <small class="text-muted"><i class="fa-solid fa-pen"></i>{{ comment.date_posted|date:'H:i, d/m/Y' }}</small>
                            </div>
                        </div> 
                    </div>
                </div>
            {% endfor %}
            <h5 class="mb-0 mt-1"><a href="{% url 'blog:blog_home' %}">&laquo; Back</a></h5>
        </div>


    </article>
    {% if user.is_authenticated %}
        <h4>Add a comment</h4>
        <form action="." method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-info mb-4" type="submit">Save</button>
        </form>
    {% else %}
        <p><a href="{% url 'login' %}">Login</a> or <a href="{% url 'users:register' %}">Signup</a> to comment</p>
    {% endif %}

{% endblock content %}