blog/urls.py
from django.urls import path


from .views import (
    PostListView,
    PostDetailView,
    # PostCreateView,
    # PostUpdateView,
    # PostDeleteView,
    # UserPostListView,
    about_view,
)

app_name = "blog"
urlpatterns = [
    path("", PostListView.as_view(), name="blog_home"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path("about/", about_view, name="blog_about"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("blog.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("users.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import register_view, profile_view, profile_update_view

app_name = "users"
urlpatterns = [
    path("register/", register_view, name="register"),
    path("profile/<int:id>/", profile_view, name="profile"),
    path("profile/<int:id>/update/", profile_update_view, name="profile_update"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, max_length=100)
    location = models.CharField(max_length=50)
    image = models.ImageField(default="default.webp", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username } Profile"

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(
        max_length=25,
        widget=forms.TextInput(attrs={"placeholder": "Max 25 Characters"}),
    )

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "password1", "password2"]


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    first_name = forms.CharField(
        max_length=25,
        widget=forms.TextInput(attrs={"placeholder": "Max 25 Characters"}),
    )

    class Meta:
        model = User
        fields = ["username", "email", "first_name"]


class ProfileUpdateForm(forms.ModelForm):
    location = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Max 50 Characters"})
    )

    class Meta:
        model = Profile
        fields = ["image", "location", "bio"]

        widgets = {
            "bio": forms.Textarea(attrs={"placeholder": "Max 100 Characters"}),
        }

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied

from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, f"Your account has been created! You can login now."
            )
            return redirect("login")
    else:
        form = UserRegisterForm()
    context = {
        "form": form,
    }
    return render(request, "users/register.html", context)


@login_required
def profile_view(request, id):
    user = User.objects.get(id=id)
    context = {
        "user": user,
    }

    return render(request, "users/profile.html", context)


@login_required
def profile_update_view(request, id):
    if not id == request.user.id:
        raise PermissionDenied()
    else:
        if request.method == "POST":
            u_form = UserUpdateForm(request.POST, instance=request.user)
            p_form = ProfileUpdateForm(
                request.POST, request.FILES, instance=request.user.profile
            )
            if u_form.is_valid() and p_form.is_valid():
                u_form.save()
                p_form.save()
                messages.success(request, f"Your account has been updated.")
                return redirect("users:profile", id)

        else:
            u_form = UserUpdateForm(instance=request.user)
            p_form = ProfileUpdateForm(instance=request.user.profile)

        context = {
            "u_form": u_form,
            "p_form": p_form,
        }

    return render(request, "users/profile_update.html", context)

users/templates/users/profile.html
{% extends 'blog/base.html' %}
{% load humanize %}
{% block title %}Profile | {{ user.username }}{% endblock title %}

{% block content %}
    <div class="content-section">
        <div class="media">
            <div class="media-body">
                <div class="profile-title">
                    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" alt="Profile {{ user.first_name }}">
                    <div class="mb-3">
                        <h2 class="account-heading">{{ user.username }}</h2>
                        {% if user == request.user %}
                            <span class="text-secondary"><i class="fa-solid fa-envelope"></i> {{ user.email }} &middot;</span>
                        {% endif %}
                        <span class="text-secondary"><i class="fa-regular fa-face-smile"></i> {{ user.first_name }}</span>
                    </div>
                </div>
                
                {% if user.profile.location %}
                    <p class="mb-1"><i class="fa-solid fa-location-dot"></i> {{ user.profile.location }}</p>
                    <p>Bio: {{ user.profile.bio }}</p>
                {% else %}
                <p class="mb-1"><i class="fa-solid fa-location-dot"></i>Unknown</p>
                <p>Bio: Unknown</p>
                {% endif %}
                <p>
                    <small>Last Login: {{ user.last_login|naturaltime }}</small><br>
                    <small>Date Joined: {{ user.date_joined|date:'H:i, d/m/Y' }}</small>
                </p>
            </div>
        </div>
        <!-- FORM HERE -->
        {% if user == request.user %}
                <div class="my-2 mb-3">
                    <a href="{% url 'users:profile_update' user.id %}" class="btn btn-secondary btn-sm mt-1 mb-1">Update Profile</a>
                    <a href="{% url 'password_change' %}" class="btn btn-outline-info btn-sm mt-1 mb-1">Change Password</a>
                </div>
        {% endif %}

        <h5 class="border-top mb-0"><a href="{% url 'blog:blog_home' %}">&laquo; Back</a></h5>
    </div>
{% endblock content %}

users/templates/users/profile_update.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Update {{ user.username }}{% endblock title %}

{% block content %}
    <div class="content-section mb-4">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary"><i class="fa-solid fa-envelope"></i> {{ user.email }}</p>
                {% if user.profile.location %}
                    <p><i class="fa-solid fa-location-dot"></i> {{ user.profile.location }}</p>
                {% endif %}
            </div>
        </div>
        <!-- FORM HERE -->
        <div class="content-section">
            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <legend class="border-bottom mb-4">
                        Profile Info
                    </legend>
                    {{ u_form|crispy }}
                    {{ p_form|crispy }}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-info">Update</button>
                    <a href="../" class="btn btn-outline-secondary">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Feuer | Register{% endblock title %}

{% block content %}
    <div class="content-section">
        <form action="." method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Join Today
                </legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-info">Sign Up</button>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Already Have An Account? <a href="{% url 'login' %}" class="ml-2">Sign In</a>
                </small>
            </div>
        </form>
    </div>
{% endblock content %}